apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: default
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client-1
          image: asia-southeast1-docker.pkg.dev/avid-atrium-414511/mugen-fc-repository/client:latest
          imagePullPolicy: Always
          env:
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: CLIENT_URL
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: AUTH_URL
            - name: BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: BUCKET_URL
            - name: GAMESERVER_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: GAMESERVER_URL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
