apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: client
  name: client-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  ports:
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: client
  sessionAffinity: ClientIP
  type: ClusterIP
