apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: client
  name: client-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30771
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: client
  sessionAffinity: ClientIP # Enable client IP session affinity
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.198.207.113
