version: "3.8"
services:
  server-auth:
    container_name: server-auth
    build: ./server-auth
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_URL=${CLIENT_URL}
      - AUTH_URL=${AUTH_URL}
      - BUCKET_URL=${BUCKET_URL}
      - GAMESERVER_URL=${GAMESERVER_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_ENV=${APP_ENV}
    restart: unless-stopped

  server-bucket:
    container_name: server-bucket
    build: ./server-bucket
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CLIENT_URL=${CLIENT_URL}
      - AUTH_URL=${AUTH_URL}
      - BUCKET_URL=${BUCKET_URL}
      - GAMESERVER_URL=${GAMESERVER_URL}
      - APP_ENV=${APP_ENV}
    restart: unless-stopped

  server-game:
    container_name: server-game
    build: ./server-game
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CLIENT_URL=${CLIENT_URL}
      - AUTH_URL=${AUTH_URL}
      - BUCKET_URL=${BUCKET_URL}
      - GAMESERVER_URL=${GAMESERVER_URL}
      - APP_ENV=${APP_ENV}
    restart: unless-stopped

  mugen-client:
    container_name: mugen-client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_AUTH_SERVER_URL=${NEXT_PUBLIC_AUTH_SERVER_URL}
      - BUCKET_URL=${BUCKET_URL}
      - NEXT_PUBLIC_GAME_SERVER_URL=${NEXT_PUBLIC_GAME_SERVER_URL}
      - NEXT_PUBLIC_GAME_SERVER_SOCKET_URL=${NEXT_PUBLIC_GAME_SERVER_SOCKET_URL}
    restart: unless-stopped
