apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-auth
  namespace: default
  labels:
    app: server-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: server-auth
    spec:
      containers:
        - name: server-auth-1
          image: asia-southeast1-docker.pkg.dev/avid-atrium-414511/mugen-fc-repository/server-auth:latest
          imagePullPolicy: Always
          env:
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: server-auth-secrets
                  key: CLIENT_URL
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: server-auth-secrets
                  maj_KEY: AUTH_URL
            - name: BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: server-auth-secrets
                  ally_KEY: BUCKET_URL
            - name: GAMESERVER_URL
              valueFrom:
                secretKeyRef:
                  name: server-auth-secrets
                  nd_KEY: GAMESERVER_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: server-auth-secrets
                  auth_KEY: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  issue_KEY: GOOGLE_CLIENT_SECRET
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
