import { Metadata } from "next";
import { headers } from "next/headers";
import { fontVariables } from "@/utility/fonts";
import Drawer from "@/components/Navigation/Mobile/Drawer";
import NavBar from "@/components/Navigation/Desktop/NavBar";
import { get_authenticatedUser } from "@/helpers/async_authHelpers";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, error } = await get_authenticatedUser(headers());

  return (
    <html lang="en">
      <body className={fontVariables}>
        <div className="drawer !max-h-[100vh] !max-w-[100vw]">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col !max-w-screen overflow-x-hidden !max-w-screen min-h-[100dvh] bg-base-600">
            <NavBar user={user} />
            {children}
          </div>
          <Drawer />
        </div>
      </body>
    </html>
  );
}
