apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-auth
  namespace: default
  labels:
    app: server-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: server-auth
    spec:
      containers:
        - name: server-auth-1
          image: asia-southeast1-docker.pkg.dev/avid-atrium-414511/mugen-fc-repository/server-auth:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: CLIENT_URL
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: AUTH_URL
            - name: BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: BUCKET_URL
            - name: GAMESERVER_URL
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: GAMESERVER_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: GOOGLE_CLIENT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
