apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: server-auth
  name: server-auth-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30753
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: server-auth
  sessionAffinity: ClientIP # Enable client IP session affinity
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 34.150.20.75
